service: first

plugins:
  - serverless-python-requirements

custom:
  baseName: ${opt:stage}-${self:service}
  pythonRequirements:
    dockerizePip: non-linux

package:
  exclude:
    - node_modules/**
    - venv/**
    - test/**

provider:
  name: aws
  runtime: python3.8
  environment:
    LOG_LEVEL: info
  logRetentionInDays: 30
  iamRoleStatements:
    - Effect: Allow
      Action:
        - xray:PutTelemetryRecords
        - xray:PutTraceSegments
      Resource: "*"

functions:
  first:
    name: ${self:custom.baseName}
    handler: src/handler.handler
    iamRoleStatementsName: ${self:custom.baseName}